application: zooudel
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon\.ico

- url: /bootstrap
  static_dir: app/static/bootstrap

- url: /css
  static_dir: app/static/css

- url: /js
  static_dir: app/static/js

- url: /images
  static_dir: app/static/images

- url: /.*
  script: app.main.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: latest